[package]
name = "kreuz-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
peniko.workspace = true

# TODO: remove
vello.workspace = true

[lints]
workspace = true
